/**
 * Re-export layer for the generated protocol surface.
 *
 * `protocol.ts` (next to this file) is GENERATED by `protons` from
 * `proto/protocol.proto` (AD-8/AD-12) — **do not edit by hand**; regenerate
 * with `pnpm generate:proto`. This file is the stable re-export layer the
 * rest of the package imports: it exposes the four messages
 * (`Block`/`Ticket`/`Tx`/`PeerInfo`) each as BOTH
 *
 *   - a message *type* (the field set, e.g. `const b: Block = { ... }`), and
 *   - a *value* namespace carrying its codecs (`Block.encode`, `Block.decode`,
 *     `Block.codec`, `Block.stream`).
 *
 * plus the full `succinctcoin` namespace for `succinctcoin.*`-style access.
 */
import { succinctcoin } from './protocol.js'

// Message field-set types (type space).
export type Block = succinctcoin.Block
export type Ticket = succinctcoin.Ticket
export type Tx = succinctcoin.Tx
export type PeerInfo = succinctcoin.PeerInfo

// Codec namespaces (value space): `codec` / `encode` / `decode` / `stream`.
export const Block = succinctcoin.Block
export const Ticket = succinctcoin.Ticket
export const Tx = succinctcoin.Tx
export const PeerInfo = succinctcoin.PeerInfo

// Full generated namespace (type + value) and the wire input types, for
// `succinctcoin.Block`-style access and `*Input` partial field sets.
export { succinctcoin } from './protocol.js'
export type { succinctcoinInput } from './protocol.js'
